server:
  port: 8080
  max-http-header-size: 48000
  servlet:
    context-path: /api/readingisgood/v1/
    encoding:
      force: true


# ========= In Memory DB ==========
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: test
    password: test
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: true
      
      
# ========= Logging ==========
logging:
  level:
    root: ERROR
    com:
      yunus: DEBUG